// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POS.Domain.Entities;

[Keyless]
public partial class VCatalogConvertionKgToOtherUnit
{
    [Column("ProductID")]
    public int? ProductId { get; set; }

    [Column("CatalogQty_Kg", TypeName = "decimal(18, 2)")]
    public decimal? CatalogQtyKg { get; set; }

    [Column("Product_KgPerUnit", TypeName = "decimal(18, 2)")]
    public decimal? ProductKgPerUnit { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? ProductQty { get; set; }

    [Required]
    [Column("Convertion_Type")]
    [StringLength(25)]
    [Unicode(false)]
    public string ConvertionType { get; set; }

    [Column("convertion_date")]
    public DateOnly? ConvertionDate { get; set; }
}